### ISSUE TITLE
issue on publishDate code

### ISSUE THREAD

**Issue by Funkytowel** [Lenir/Naver-Blog-Backup#4]
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Users/1111/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/1111/anaconda3/lib/python3.6/site-packages/NaverBlogCrawler/NaverBlogCrawler.py", line 127, in run
    postingCrawler.run()
  File "/Users/1111/anaconda3/lib/python3.6/site-packages/NaverBlogCrawler/NaverBlogPostCrawler.py", line 113, in run
    self.postSetup()
  File "/Users/1111/anaconda3/lib/python3.6/site-packages/NaverBlogCrawler/NaverBlogPostCrawler.py", line 61, in postSetup
    self.postDate = self.getPostDate()
  File "/Users/1111/anaconda3/lib/python3.6/site-packages/NaverBlogCrawler/NaverBlogPostCrawler.py", line 85, in getPostDate
    publishDate = re.search(publishDateRegExpr, publishDate).group()
AttributeError: 'NoneType' object has no attribute 'group'

Tested in OSX

**Comment by appleman1232** [comment]
fix for yourself retard.
